name: bd2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - clang
  - clangxx
  - pip:
      - Flask
      - pymongo
      - bcrypt
      - hnswlib
      - numpy
      - sentence-transformers
