name: bd2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - gxx
  - pip:
      - Flask>=2.0.0
      - pymongo>=4.0
      - bcrypt>=3.2.0
      - hnswlib>=0.8.0
      - numpy>=1.21.0
      - sentence-transformers>=2.2.0
